### ISSUE TITLE
Missing computer after upgrade 2.6

### ISSUE THREAD

**Issue by raydelgg** [OCSInventory-NG/OCSInventory-ocsreports#722]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian9.6

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0.33
Mysql / Mariadb / Percona version : mariaDB 10.1.37
Apache version :  2.4.25

### OCS Inventory informations
Ocsreports version : 2.6

### Problem's description
After migrate from 2.6-RC to 2.6, some computer aren't display in the web. the record still in the db, and are updated but no are displayed.
The 'hidden' computers have different OS (Ubuntu, Debian, WindowsXP and Windows10), the agent does not seem to be the problem, since they have unix_agent, windows_agent and injector_pl.

Thanks for your help (and sorrry for my english)
Raydel

**Comment by sokatra** [comment]
i have the same problem - about 20 of 1000 computers aren't visible in the webgui

**Comment by Bexounet** [comment]
Same problem here on a test platform.
My test plaform was in OCS 2.5 
Ubuntu 18.04.1 LTS, 
PHP Version : 7.2.17
Web Server : Apache/2.4.29 (Ubuntu)
Database Server : Ubuntu 18.04 version 10.1.38-MariaDB-0ubuntu0.18.04.1

19888 computers inventoried with injector_pl from my Quality Assurance platform (the QA receive the inventory from the Production platform with injector.pl).
They are mainly Ubuntu, Redhat, Windows, Solaris, AIX, SUSE linux.

After upgrade : 17940 computers are displayed.

The "missing computers" are : 
385	Ubuntu 16.04 LTS
345	Red Hat Enterprise Linux ES release 4 (Nahant Update 7)
344	Ubuntu 14.04.2 LTS
234	Ubuntu 12.04.1 LTS
112	SUSE Linux Enterprise Server 11 (x86_64)
83	Red Hat Enterprise Linux Server release 6.4 (Santiago)
69	Red Hat Enterprise Linux Server release 6.9 (Santiago)
46	Red Hat Enterprise Linux Server release 5.11 (Tikanga)
36	Red Hat Enterprise Linux ES release 4 (Nahant Update 8)
33	Red Hat Enterprise Linux Server release 5.6 (Tikanga)
30	Ubuntu 12.04.5 LTS
21	Red Hat Enterprise Linux Server release 5.5 (Tikanga)
20	Red Hat Enterprise Linux Server release 6.6 (Santiago)
18	Ubuntu 14.04.5 LTS
17	Red Hat Enterprise Linux Server release 6.3 (Santiago)
16	Red Hat Enterprise Linux Server release 6.5 (Santiago)
15	Red Hat Enterprise Linux Server release 5.4 (Tikanga)
11	Red Hat Enterprise Linux Server release 5.7 (Tikanga)
10	Red Hat Enterprise Linux Server release 5.8 (Tikanga)
7	Ubuntu 12.04.4 LTS
6	Ubuntu 14.04 LTS
5	SunOS 5.10
4	CentOS release 6.7 (Final)
3	Linux
3	AIX 7.1
3	Red Hat Enterprise Linux Server release 6.1 (Santiago)
2	Ubuntu 14.04.4 LTS
1	Debian GNU/Linux stretch/sid
1	Red Hat Enterprise Linux ES release 4 (Nahant Update 3)
1	CentOS release 5.11 (Final)
1	Red Hat Enterprise Linux Server release 5.9 (Tikanga)
1	Red Hat Enterprise Linux ES release 4 (Nahant Update 9)
1	Red Hat Enterprise Linux Server release 6.2 (Santiago)
1	Red Hat Enterprise Linux AS release 4 (Nahant Update 8)
1	Ubuntu 14.04.1 LTS

No Windows computers are missing. The Windows agent allways make a full inventory on my plateform.
The Unix agent sometime make an incomplete inventory on my plateform, with some missing category (no network card, no bios in the inventory). I think the problem occurs when the agent have some problem when it try to call dmidecode.   

I suspect the "missing computers" doesn't have a fully completed inventory... but I can't check the 1948 computers that are not displayed. 

PS : I have "before" and after" snapshots of my test server.

**Comment by sokatra** [comment]
i can find all computer via "various criteria search" - but not in the overwiew
I also tested the following
1. export one computer(in Ocs-Inventory 2.5)  which can't be found in Ocs-Inventory 2.6 
2. import this computer into empty database in version 2.6 
Result - on computer overview - i can't find the computer object - but i can search via various criteria for the computer name - the computer will be found!!
Nearly all computer which will not displayed in computer overview  are Apple Computers - but also some windows computers

**Comment by Bexounet** [comment]
Sokatra, same behavior here. 

I can find all my inventoried computers with "search with various critera", but not with "all computers" menu.

**Comment by Bexounet** [comment]
I think the "All computers" pages show all the computers with network card inventoried.

@sokatra can you confirm this ? does your Apple computers which are not displayed in "all computer" page have a network card int their inventory ?

**Comment by Bexounet** [comment]
I found the origin of the problem 
[https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/656/](url)
Microsoft would say "this behavior is by design". 
But "All computers" should be "all computers", not "all computers with network interface up". After all, OCS inventory allow a local import of a non-network connected computer.  And Unix Agent fails quite often to detect network interface.

**Comment by pchamo** [comment]
And until de fix is included, the workaround is to comment this line?

//$queryDetails .= " AND n.STATUS = 'up' ";

**Comment by charleneauger** [comment]
Hi @raydelgg @sokatra @Bexounet @pchamo,

This bug has been fixed with PR #771 

Best regards,
Charlene Auger

**Comment by raydelgg** [comment]
> Hi @raydelgg @sokatra @Bexounet @pchamo,
> 
> This bug has been fixed with PR #771
> 
> Best regards,
> Charlene Auger

Hi Charlene, in the PR#771, the problem is fixed,  upgrading de ocs-agent, in my case I have some pcs without network. This computer never showup in the "all computer" list

**Comment by Bexounet** [comment]
> Hi @raydelgg @sokatra @Bexounet @pchamo,
> 
> This bug has been fixed with PR #771
> 
> Best regards,
> Charlene Auger

Hi @charleneauger 

I agree with @raydelgg, I think the PR #771 doesn't correct this bug. 
I still don't understand the reason of the PR #656 which cause this bug. 

IMHO, this issues should be still open.

**Comment by pchamo** [comment]
I don't understand the purpose of this line:

// STATUS NETWORK INTERFACE UP
$queryDetails .= " AND n.STATUS<>'down' ";

As I commented, some of my computers had status down, so for me, the bug doesn't solve the issue.

**Comment by charleneauger** [comment]
Hi @raydelgg @pchamo @Bexounet ,

I fixed the missing computer problem :)
Thank's for your reports !

Best Regards,
Charlene Auger

**Comment by Bexounet** [comment]
Thanks !
